name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set execute permissions
      run: chmod +x pipeline.sh lab.sh

    - name: Run pipeline script
      run: ./pipeline.sh

